context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
      est: 1 l√µik
    value: 1 paragraph
description:
  swe: Moderna
  eng: Modern
  est: Veebikorpus
id: older_fiction
mode:
  - name: default


pos_attributes:
  - baseform: lemma
  - pos: epos
  - msd: msd

struct_attributes:
  - doc_title: title
  - doc_year: year
  - doc_date: date

    

title:
  swe: 'Web 23'
  eng: 'Web 23'
  est: 'Vanem ilukirjandus'
within:
  - label:
      eng: sentence
      swe: mening
      est: lause
    value: sentence
